version: 2

builds:
  - main: ./cmd/pipe
    binary: pipe
    ldflags:
      - -s -w
      - -X github.com/mathew-builds/pipe-dev/pkg/version.Version={{.Version}}
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz

changelog:
  sort: asc
